
DELETE FROM CT_DONGHOCPHI 
WHERE EXISTS (SELECT HP.MASV, HP.NIENKHOA, HP.HOCKY FROM HOCPHI AS HP JOIN CT_DONGHOCPHI AS CTHP ON HP.MASV = CTHP.MASV 
WHERE HP.HOCKY = CTHP.HOCKY AND HP.HOCKY = CTHP.HOCKY)

select * 
  from HOCPHI
  where exists (
  select 1 
    from DANGKY
    where DANGKY.MASV = HOCPHI.MASV
    );